type Exercise {
  id: ID!
  exercise: Int!
  deps: Int
}


type Query {
  getExerciseListByIds(ids: [ID!]): [Exercise!]
  getExerciseById(id: ID): Exercise
  getExerciseListByScheduleId(scheduleId: ID): [Exercise!]
  getExerciseListByExercisePresetId(exercisePresetId: ID): [Exercise!]
}

input CreateExerciseByScheduleInput {
  scheduleId: Int!
  exerciseId: [Int!]
}
input CreateExerciseByExercisePresetInput {
  exercisePresetId: Int!
  exerciseId: [Int!]
}

input UpdateExerciseInput {
  id: String!
  exerciseId: Int!
}

type Mutation {
  createExerciseBySchedule(exercise: CreateExerciseByScheduleInput): Exercise
  createExerciseByExercisePreset(exercise: CreateExerciseByExercisePresetInput): Exercise

  updateExercise(exercise: UpdateExerciseInput): Exercise
  updateExerciseListByScheduleId(scheduleId: Int, newExercise: [Int!], deleteExerciseId: [Int!]): [Exercise]
  updateExerciseListByExercisePresetId(exercisePresetId: Int, newExercise: [Int!], deleteExerciseId: [Int!]): [Exercise]

  deleteExerciseById(id: ID): String
}