enum WeightUnit {
  kg
  lbs
}

type Sets {
  id: ID!
  exerciseId: ID!
  repeat: Int!
  isDone: Boolean!
  weightUnit: WeightUnit!
  weight: Float!
  duration: Int!
}

input CreateSetsInput {
  id: ID!
  exerciseId: ID!
  repeat: Int!
  isDone: Boolean!
  weightUnit: WeightUnit!
  weight: Float!
  duration: Int!
}

input UpdateSetsInput {
  id: ID!
  repeat: Int!
  isDone: Boolean!
  weightUnit: WeightUnit!
  weight: Float!
  duration: Int!
}

type Query {
  getSetByIds(ids: [ID!]): [Sets!]
  getSetById(id: ID!): Sets
  getSetListByExerciseId(id: ID!): [Sets!]
}

type Mutation {
  createSet(sets: CreateSetsInput!): Sets
  updateSet(sets: UpdateSetsInput!): Sets
  deleteSetById(id: ID): String
}
