type ExercisePreset {
  id: ID!
  name: String!
  deps: Int!
}
type Exercise {
  id: ID!
  exercise: Int!
}

type ExercisePresetWithList {
  id: ID!
  name: String!
  deps: Int!
  exerciseList: [Exercise!]
}

type Query {
  getExercisePresetList(page: Int, size: Int): [ExercisePresetWithList!]
  getExercisePresetByIds(ids: [ID!]): [ExercisePreset!]
  getExercisePresetById(id: ID): ExercisePreset
}

input CreateExercisePresetInput {
  name: String!
}

input UpdateExercisePresetInput {
  id: ID!
  name: String!
  deps: Int!
}

type Mutation {
  createExercisePreset(exercisePreset: CreateExercisePresetInput): ExercisePreset
  updateExercisePreset(exercisePreset: UpdateExercisePresetInput): ExercisePreset
  deleteExercisePreset(id: ID!): String
  saveScheduleAsExercisePreset(scheduleId: ID!, name: String!): ExercisePreset
}
