type Exercise {
  id: ID!
  exercise: Int!
}

type ExerciseList {
  exerciseList: [Exercise!]
}


type Query {
  getExerciseListByIds(ids: [ID!]): [Exercise!]
  getExerciseById(id: ID): Exercise
  getExerciseByExercisePresetId(id: ID): [Exercise!]
  getExerciseListByScheduleId(scheduleId: ID): [Exercise!]
}

input CreateExerciseByScheduleInput {
  scheduleId: Int!
  exerciseId: [Int!]
}
input CreateExerciseByExercisePresetInput {
  exercisePresetId: Int!
  exerciseId: [Int!]
}

input UpdateExerciseInput {
  id: String!
  exerciseId: Int!
}

type Mutation {
  createExerciseBySchedule(exercise: CreateExerciseByScheduleInput): Exercise
  createExerciseByExercisePreset(exercise: CreateExerciseByExercisePresetInput): Exercise

  updateExercise(exercise: UpdateExerciseInput): Exercise
  upcateExerciseListBySchedule(newExercise: [Int!], deleteExercise: [Exercise!]): Exercise

  deleteExerciseById(id: ID): String
}