type Exercise {
  id: ID!
  exercise: Int!
}

type ExerciseList {
  exerciseList: [Exercise!]
}


type Query {
  getExerciseListByIds(ids: [ID!]): [Exercise!]
  getExerciseById(id: ID): Exercise
  getExerciseByExercisePresetId(id: ID): [Exercise!]
  getExerciseListByScheduleId(scheduleId: ID): [Exercise!]
}

input CreateExerciseInput {
  exerciseId: Int!
  scheduleId: Int!
}

input UpdateExerciseInput {
  id: String!
  exerciseId: Int!
}

type Mutation {
  createExercise(exercise: CreateExerciseInput): Exercise
  updateExercise(exercise: UpdateExerciseInput): Exercise
  deleteExerciseById(id: ID): String
}