name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    if: github.repository == 'cjhih456/fitness-recoder'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      # Pick your own package manager and build script
      - run: yarn install
      - run: yarn build
      - run: cp ./apps/web/dist/index.html ./apps/web/dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'apps/web/dist'
  # Deployment job
  deploy:
    if: github.repository == 'cjhih456/fitness-recoder'
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Specify runner + deployment step
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4